name       : vid.stab
version    : 1.1
release    : 1
source     :
    - git|git://github.com/georgmartius/vid.stab.git : 2d82492533bf5004bc2c4f8213a1b622c45f6a44
license    : GPL-2.0
component  : multimedia.library
summary    : Video stabilization library
description: |
    Vidstab is a video stabilization library which can be plugged-in with Ffmpeg and Transcode.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
